[package]
name = "pagbar"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.22.0"
egui-winit = "0.22.0"
egui_glow = { version = "0.22.0", features = ["winit"] }
glow = "0.12.2"
glutin = "0.30.8"
glutin-winit = "0.3.0"
log = "0.4.18"
raw-window-handle = "0.5.2"
thiserror = "1.0.40"
