[package]
name = "pagbar"
version = "0.1.0"
edition = "2021"

[dependencies]
as-raw-xcb-connection = "1.0.0"
egui = "0.22.0"
egui_glow = "0.22.0"
env_logger = "0.10.0"
gl = "0.14.0"
#TODO: disable unecessary features
glutin = "0.30.8"
thiserror = "1.0.40"
x11 = { version = "2.21.0", features = ["xlib", "glx"] }

xcb = { version = "1.2.1", features = ["randr", "xlib_xcb", "glx"] }
