[colors]
background = "#000000"
text = "#ff2255"
text-secondary = "#888888"

[bar.main]
monitor = 0
position = "top"
size = 60

# multi-bar
# [bar.second]
# monitor = 1
# position = "top"
# size = 60

# UNIMPLEMENTED
# modules
# [module.disk]
# panel = "last"
# format-prefix = "/ "
# color-prefix = "text"
# format = "{}%"
# color = "text-secondary"

# [module.ram]
# panel = "last"
# format-prefix = "ram "
# color-prefix = "text"
# format = "{}%"
# color = "text-secondary"

# [module.cpu]
# panel = "last"
# format-prefix = "cpu "
# color-prefix = "text"
# format = "{}°C"
# color = "text-secondary"

# [module.clock]
# panel = "middle"
# format = "%H\n:%M:\n%S"
# color = "text"
