[colors]
background = "#000000"
text = "#ff2255"
text-secondary = "#888888"

[bar.main]
monitor = 0
position = "left"
size = 220
layout = { _ = 1, clock = 2, system = 1 }

[bar.second]
monitor = 1
position = "top"
size = 60
layout = { clock = 1 }

[panels]
_ = ["clock"]
clock = ["clock"]
system = ["disk", "ram", "cpu"]

